version: "3.7"

x-haproxy-defaults: &haproxy-service
  image: "haproxy:2.0-alpine"
  volumes:
      - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"

x-keepalived-defaults: &keepalived-service
  image: "osixia/keepalived:2.0.19"
  cap_add:
    - NET_ADMIN
    - NET_BROADCAST
    - NET_RAW
  environment:
    KEEPALIVED_COMMAND_LINE_ARGUMENTS: >-
      --log-detail
#      -–dont-release-vrrp
#      -–dont-release-ipvs
#      --log-detail
#      --dump-conf

services:
  runner:
    image: "runner:local"
    build:
      context: .
    network_mode: host

  keepalived-a:
    <<: *keepalived-service
    network_mode: host
    volumes:
      - "./keepalived/proxy-a/keepalived.conf:/usr/local/etc/keepalived/keepalived.conf:ro"
      - "./keepalived/notify.sh:/container/service/keepalived/assets/notify.custom.sh:ro"

  keepalived-b:
    <<: *keepalived-service
    network_mode: host
    volumes:
      - "./keepalived/proxy-b/keepalived.conf:/usr/local/etc/keepalived/keepalived.conf:ro"
      - "./keepalived/notify.sh:/container/service/keepalived/assets/notify.custom.sh:ro"

  haproxy-a:
    <<: *haproxy-service
    network_mode: host

  haproxy-b:
    <<: *haproxy-service
    network_mode: host
